### ISSUE TITLE
Finished download should be filtered away / hidden

### ISSUE THREAD

**Issue by bthusby** [YodaDaCoda/chrome-transmission-remote-plus#10]
When a download is finished I would suggest to hide it from the dropdown menu. Presently it shows with green color, the same as seeding. I would like to keep the history around in Transmission, but I don't want it to show in the 'Remote Transmission ++' dropdown menu.

**Comment by YodaDaCoda** [comment]
Added an 'Active' option in the filtering box, which pretty much fixes this. Please test and provide feedback. Commit a96feb6957dfaff3547224fb1e2aca8f1a778b0d refers.

**Comment by YodaDaCoda** [comment]
Closing due to lack of response.

**Comment by bthusby** [comment]
Sorry, forgot to reply. It works now :)
