### ISSUE TITLE
torrent list is blank since 0.9.9.8

### ISSUE THREAD

**Issue by chenks** [YodaDaCoda/chrome-transmission-remote-plus#13]
ever since the previous update all i get (on muliple devices) is the header at the top with the logo and the torrent numbers, but below where you see the torrents listed i just have a blank white space.

i am running 0.9.9.8 on two systems (one mac one windows) and experience the same on both.
problem wasn't there before either 0.9.9.7 or 0.9.9.8.

![screen shot 2015-04-14 at 17 58 46](https://cloud.githubusercontent.com/assets/11945919/7142387/0920a6d2-e2d0-11e4-8bdd-0599a3c3ddc1.png)

**Comment by YodaDaCoda** [comment]
Try changing the filter from "Paused/Completed" to "All". This looks like a side-effect of fixing the filtering.

**Comment by chenks** [comment]
ah yes, that shows them all.
but the paused/completed filter isn't working though.

**Comment by YodaDaCoda** [comment]
That should really just be called "Stopped". If a torrent is completed but seeding, it won't show under "Paused/Completed".

**Comment by chenks** [comment]
OK that makes sense now.

**Comment by YodaDaCoda** [comment]
All good?

**Comment by chenks** [comment]
seems to be.
i think what threw me is that the filter changed during the update, and i didn't think to look at that.

**Comment by YodaDaCoda** [comment]
Awesome. Thanks for alerting me to this. I've released an update that will fix this for anybody else.
