### ISSUE TITLE
Latest update (2015-06-03 v1.0.0) doesn't save settings.

### ISSUE THREAD

**Issue by sethrd** [YodaDaCoda/chrome-transmission-remote-plus#19]
If Chrome is closed and reopened, the options.html?newvar=true page is loaded with default vaults.

**Comment by wader** [comment]
@YodaDaCoda see comment on c3cc9f3

**Comment by YodaDaCoda** [comment]
Fixed in c4fd07bffcd7be325093eddecc5a67e56c97ad50. Pushing release to market now.
