### ISSUE TITLE
Add option to start torrents in Paused state

### ISSUE THREAD

**Issue by YodaDaCoda** [YodaDaCoda/chrome-transmission-remote-plus#23]
Done in 9db570aa8664e38a103660e4998573e3c4909a80. Needs testing.

**Comment by InsomniacSoftware** [comment]
Hi, I'm the person that asked for this feature in the Chrome store.  You mentioned that this was added and pushed out but I'm not seeing it.  I deleted and reinstalled version 1.0.3 from the store.  Did 1.0.3 include this feature?

I looked at the code change and see where it should appear in the options screen but it isn't being displayed.  The Download box only contains the regular "Default Click Action" and "Location" boxes.
Any ideas?

If you would like, I would be willing to test it directly so you don't need to push out untested code to everyone.

**Comment by slokhorst** [comment]
There is currently a bug, which is fixed by #37. After that, this works.

**Comment by YodaDaCoda** [comment]
Fixed by #37
