### ISSUE TITLE
Relative links are sent rather than absolute

### ISSUE THREAD

**Issue by gaelb** [YodaDaCoda/chrome-transmission-remote-plus#24]
<img src="https://cloud.githubusercontent.com/assets/949754/12948984/d9637e64-d005-11e5-89b6-7ae0f39cae02.png" width="300"  />

The link sent to transmission may be relative and the base domain may be not sent. 

In inject.js:40, instead of:`
    var url = $(this).attr("href");`

it is preferable to get the absolute url
`var url = this.href;
`
see: [http://stackoverflow.com/questions/2639070/get-the-full-uri-from-the-href-property-of-a-link](url)

**Comment by YodaDaCoda** [comment]
Thanks for the report. I'll fix this later today.

**Comment by timothympace** [comment]
I have been dealing with this issue as well. The solution suggested by gaelb is what I came up with as well. It doesn't appear this ever got updated in the code.

**Comment by iancorbitt** [comment]
This solved a random issue I was having as well.

**Comment by YodaDaCoda** [comment]
Fixed when #33 was merged
