### ISSUE TITLE
Inject.js needs to have line 56 commented out

### ISSUE THREAD

**Issue by jeffehobbs** [YodaDaCoda/chrome-transmission-remote-plus#27]
Otherwise that debug statement clutters the console for everyone. See:

https://github.com/jeffehobbs/chrome-transmission-remote-plus/commit/5ada881064e8b939a2cc468dee31cf82d0c0ffb2

**Comment by YodaDaCoda** [comment]
Closed by c472296d5ddf0fda2cc87a6ac3149cb51ca0e78e
