### ISSUE TITLE
Incompatible with Transmission 2.92 / path not absolute error

### ISSUE THREAD

**Issue by GldRush98** [YodaDaCoda/chrome-transmission-remote-plus#28]
Hello, since updating Transmission to version 2.92 when I attempt to add a torrent, I receive "download directory path is not absolute" error message.  I can still see torrents in Transmission, it just seems to be the adding functionality that is broken.
Thanks.

**Comment by iancorbitt** [comment]
It doesn't work if you use "default directory". I had to add a custom directory/label and then select that every time.

**Comment by judders** [comment]
Same issue.Running Transmission 2.92. Cant add torrents when using "Default Directory"
Have to select custom directory every time. Very annoying.

**Comment by YodaDaCoda** [comment]
I don't have time to investigate/fix this. If anyone can supply a PR I will test and gratefully accept.

**Comment by judders** [comment]
Thank you zsorizs. Much appreciated.  This fixed the problem i was having.

**Comment by iancorbitt** [comment]
@zsorizs That did the trick. Got any ideas on why it won't save the default click setting though?

**Comment by zsorizs** [comment]
@iancorbitt made a separate pull request for that (haven't found an issue to reference)

**Comment by YodaDaCoda** [comment]
@zaorizs Thanks for your pull requests. They look good. I'll merge and push a new version of the extension to the Chrome web store in a few days.

**Comment by YodaDaCoda** [comment]
I've pushed a new version to the Chrome web store incorporating @zsorizs's changes.
