### ISSUE TITLE
Show Download Popup Option Broken

### ISSUE THREAD

**Issue by aobme** [YodaDaCoda/chrome-transmission-remote-plus#34]
Recent update broke the download popup option. Unchecking the box on the options page does not supres the popup dialog anymorel

Now the default behavior on install is that it is not checked, and the dialog appears. Relentlessly

**Comment by TalZiv** [comment]
This bug should be fixed by the developer, in the meanwhile you can fix it by press F12 in the plugin option.
and change the dlPopup value to false like in the image below:
![image](https://cloud.githubusercontent.com/assets/22313897/25862450/c62f5d94-34f0-11e7-93d6-856cc96ee260.png)
