### ISSUE TITLE
No images in Chrome webstore

### ISSUE THREAD

**Issue by YodaDaCoda** [YodaDaCoda/chrome-transmission-remote-plus#38]
Help wanted as I am not actively using the extension at this time.

Images should be 1,280x800 or 640x400 to comply with Chrome webstore requirements.

Images should show the list of torrents in various states and stages of completion. All torrents must be legally obtained, i.e. no TV shows / movies / games. Recommend Linux distributions and such.

**Comment by slokhorst** [comment]
Something like this?

https://sebbro.nl/remotetransmission/extension.png
https://sebbro.nl/remotetransmission/options.png
https://sebbro.nl/remotetransmission/rightclick.png

I can make more if you want.

Should I put them somewhere in this repository?

**Comment by YodaDaCoda** [comment]
That's fantastic! Could you put them in a 'webstore' folder and make a PR please?
