### ISSUE TITLE
Popup doesn't show torrents

### ISSUE THREAD

**Issue by slokhorst** [YodaDaCoda/chrome-transmission-remote-plus#39]
After commit 2192d13, the torrent popup is empty after clicking the extension icon.

The top interface elements are shown (Icon, number of torrents, DL/UL rate), but the list of torrents is missing.

**Comment by YodaDaCoda** [comment]
Fixed in a5456be3f83c4afd0389abe3aa2ccb0a1a9f3292
Thanks for reporting

**Comment by slokhorst** [comment]
Confirmed fixed :)
