### ISSUE TITLE
fixing nginx http2 + remote transmission++

### ISSUE THREAD

**Issue by shtinkov** [YodaDaCoda/chrome-transmission-remote-plus#57]
I have transmission-daemon which is listening on localhost. In order to access it i have this configuration in nginx:

>    location /transmission {
>       proxy_set_header  X-Real-IP  $remote_addr;
>       proxy_set_header  X-Forwarded-For $proxy_add_x_forwarded_for;
>       proxy_set_header  Host $http_host;
>       proxy_redirect    off;
>       proxy_pass        http://127.0.0.1:9091/transmission;
>       proxy_pass_request_body on;
>       proxy_pass_request_headers on;
>       proxy_pass_header X-Transmission-Session-Id;
>    }  

Nginx is also configured for http2.  In this case Remote Transmission++ is unable to connect to transmission. Problem is that extension expects in fail function errorThrown==='Conflict' but with http2 this string is empty. I made a small patch in order to resolve this:

```
--- background.js.orig  2018-01-25 04:42:59.000000000 +0200
+++ background.js       2023-09-01 15:16:16.963952091 +0300
@@ -62,7 +62,7 @@
     }
   })
   .fail(function (jqXHR, textStatus, errorThrown) {
-    if (errorThrown === 'Conflict') {
+    if (errorThrown === 'Conflict'|| jqXHR.status==409) {
       // X-Transmission-Session-Id should only be included if we didn't include it when we sent our request
       let xSid = jqXHR.getResponseHeader('X-Transmission-Session-Id');
       localStorage.sessionId = xSid;
  

```
And now everything is fine. This patch should also preserve the original behavior with HTTP1.1 
If you find this useful please include it in the next release.

**Comment by YodaDaCoda** [comment]
fixed in #49
